### ISSUE TITLE
devServer.outputPath not defined

### ISSUE THREAD

**Issue by vhmth** [gajus/write-file-webpack-plugin#22]
I noticed that https://github.com/gajus/write-file-webpack-plugin/commit/f8abd09b0a475b27f16b2332303702b8c57a6594 has made it so the error below gets thrown. I did some debug printing and noticed that `compiler.options.devServer.outputPath` actually does exist, but `_.has` is returning false for some reason (bad babel build?).

```
/Users/vinay/Code/opentest/Engage/node_modules/write-file-webpack-plugin/dist/index.js:144
                    throw new Error('output.path is not accessible and devServer.outputPath is not defined. Define devServer.outputPath.');
                    ^

Error: output.path is not accessible and devServer.outputPath is not defined. Define devServer.outputPath.
    at setup (/Users/vinay/Code/opentest/Engage/node_modules/write-file-webpack-plugin/dist/index.js:144:27)
    at Compiler.<anonymous> (/Users/vinay/Code/opentest/Engage/node_modules/write-file-webpack-plugin/dist/index.js:158:18)
    at Compiler.applyPlugins (/Users/vinay/Code/opentest/Engage/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/vinay/Code/opentest/Engage/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/vinay/Code/opentest/Engage/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/Users/vinay/Code/opentest/Engage/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/Users/vinay/Code/opentest/Engage/node_modules/webpack/lib/Compiler.js:58:19)
    at /Users/vinay/Code/opentest/Engage/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/vinay/Code/opentest/Engage/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/Users/vinay/Code/opentest/Engage/node_modules/webpack/lib/Compiler.js:272:8)
```

**Comment by gajus** [comment]
I would need a repository that can reproduce this behaviour to investigate this further/ fix it.

**Comment by vhmth** [comment]
Hey man just checked in and really investigated this. This was definitely my fault - I wasn't importing my webpack configuration correctly. Sorry about that!
