### ISSUE TITLE
Unexpected token - defaultParameters

### ISSUE THREAD

**Issue by trmjoa** [gajus/write-file-webpack-plugin#27]
Hi,

After the latest release the plugin no longer works on node 4 or 5 because default parameters is not support on these versions.

```
exports.default = (userOptions = {}) => {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> 
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Is this intended? (Node 4 LTS is officially supported until april 2017)

**Comment by gajus** [comment]
Fixed in https://github.com/gajus/write-file-webpack-plugin/tree/v3.4.1

**Comment by gajus** [comment]
Just noticed that you said v4 – yes, v4 has been dropped. v5 is supported, though.

**Comment by trmjoa** [comment]
Thanks. I actually was testing on 5. Just included 4 in the issue since its LTS. Thanks for the quick response
